[package]
name = "framed_pay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
actix-web = "4"
env_logger = "0.10.0"
actix-files = "0.6.2"
serde_json = "1.0.106"
actix-cors = "0.6.4"
chrono = { version = "0.4.30", features = ["serde"] }
dotenv = "0.15.0"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
sqlx = { version = "0.7.1", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
jsonwebtoken = "8.3.0"
argon2 = "0.5.2"
rand_core = { version = "0.6.4", features = ["std"] }
validator = { version = "0.16.1", features = ["derive"] }
actix-web-validator = "5.0.1"
derive_more = "0.99.17"
